### PR TITLE
Input + Textarea selection API

### PR DESCRIPTION
**Pull request by yaycmyk**
This is based on the work in https://github.com/tmpvar/jsdom/pull/804, with some tweaks to correct a slight deviation from the spec in the node `value` setter.

Tests included.

@domenic

### CODE REVIEW

**Comment by yaycmyk** [comment]
Anything I need to change @domenic?

**Comment by domenic** [comment]
LGTM aside from the test format change. Excited!!

**Comment by yaycmyk** [comment]
@domenic Alrighty, done porting over to web platform format. Could I get another looksee? :)

**Comment by domenic** [comment]
Looks great, thank you so much!! All merged. Really impressive work; I'm glad you were up for contributing to jsdom, and we'd love to see more of you in the future :)

**Comment by yaycmyk** [comment]
:tada: you'll see more of me, I enjoyed working on this!

**Pull request closed without merging**
