### PR TITLE
add wholeText property

### LINKED ISSUE #1397: Text.wholeText Support
According to https://developer.mozilla.org/en-US/docs/Web/API/Text/wholeText, in normal browsers

```
var text = document.createTextNode('some text')
console.log(text.wholeText) // => 'some text'
```

but in `jsdom` it gets 'undefined'.

### PR DESCRIPTION
**Pull request by jdanyow**
fixes #1397

### CODE REVIEW

**Comment by jdanyow** [comment]
```
npm run test-mocha -- test/living-dom/text-node-whole-text.js
```

**Comment by domenic** [comment]
Thanks, but per Contributing.md, for new web platform features we don't create Mocha tests, but instead web platform tests. Could you follow the instructions there for either finding or writing web platform tests?

**Comment by jdanyow** [comment]
my bad- I should have read that more carefully

**Comment by jdanyow** [comment]
Hopefully this looks a bit better. I couldn't find an existing web platform test that exercised `wholeText` so I added one. Let me know if any other changes are required.

**Comment by niieani** [comment]
@domenic this being a non-breaking addition, how soon do you think this could ship in a new version on NPM? Lack of this feature is currently stopping the server-renderer for the Aurelia framework from working. Many thanks!

**Comment by domenic** [comment]
Unfortunately I can't provide an estimate at this time. I'm currently in the middle of some personal stuff which is getting in the way of my ability to work on open source. If he has time, maybe @Sebmaster would be able to finish review/merge/release.

**Comment by jdanyow** [comment]
Thanks @domenic, @Sebmaster. Your hard work is appreciated! Let me know if anything in this PR requires changes.

**Comment by domenic** [comment]
Really great PR! New release coming with it sometime today.

**Pull request merged**
