### PR TITLE
updated package.json devDependency

### PR DESCRIPTION
**Pull request by EsrefDurna**
updated package ecstatic from 2.1.0 to 2.2.1
 Npm link :  https://www.npmjs.com/package/ecstatic
 Repository link : https://github.com/jfhbrook/node-ecstatic/releases

### CODE REVIEW

**Comment by TimothyGu** [comment]
FYI these look like automated pull requests: https://github.com/EsrefDurna?tab=overview&from=2017-06-01&to=2017-06-12

**Comment by EsrefDurna** [comment]
Its easy to find recursive dependency upgrades, no need to automation, 
Hard part is to run test

**Comment by domenic** [comment]
The package specifier is already ^2.1.0, so 2.2.1 will be installed. There's no need for this kind of PR.

**Comment by EsrefDurna** [comment]
Ok

**Pull request closed without merging**
