### PR TITLE
Create composer.json

### PR DESCRIPTION
**Pull request by paladox**
Adding composer.json so it can be added to packagist.

This repo is required by some repos using packagist.

### CODE REVIEW

**Comment by domenic** [comment]
Not interested. Use npm.

**Comment by paladox** [comment]
It won't. I searched for the package on packagist but won't come up with it. I try adding the repo to it and it says Carnot find composer.json.

**Comment by Joris-van-der-Wel** [comment]
Why not use something like this: https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/index.md

**Comment by paladox** [comment]
Didn't know of that one. How would I just do something like 
{
    "extra": {
        "asset-repositories": [
            {
                "type": "bower-vcs",
                "url": "https://github.com/vendor/exemple-asset-name.git"
            }
        ]
    }
}
for this. 

Since it would be harder for others to depend on this repo since you would have to tell them to do it like this.

**Pull request closed without merging**
