### PR TITLE
Implement of DOMParser

### LINKED ISSUE #1341: support DOMParser
https://developer.mozilla.org/en/docs/Web/API/DOMParser

### PR DESCRIPTION
**Pull request by kentcdodds**
Closes #1341
References #1368

### CODE REVIEW

**Comment by kentcdodds** [comment]
This is still a WIP. I thought I should push this up to make sure I'm going in the right direction and get some feedback. The implementation is copied from @lehni's [comment](https://github.com/tmpvar/jsdom/issues/1368#issuecomment-175961668). Looks like it's incomplete. Feedback is welcome! Forgive me of my ignorance if some of what I have in here is obviously wrong. This is not an API I'm familiar with.

**Comment by Sebmaster** [comment]
Try to find web-platform-tests which test the API instead of writing your own. If there's something not tested there, add them to the to-upstream folder.

**Comment by lehni** [comment]
That's how we have it implemented as a work-around in paper.js currently: https://github.com/paperjs/paper.js/blob/develop/src/node/window.js#L58

It's definitely incomplete. I meant to work on this but have very little time to do so at the moment unfortunately.

**Comment by kentcdodds** [comment]
I'm sorry everyone, I don't know if I'm going to get time to work on this again for a while. Someone else can feel free to pick up where I left off. :-/

**Pull request closed without merging**
