### PR TITLE
Don't add timer if 'this' or 'this._document' are undefined or null

### PR DESCRIPTION
**Pull request by Enverbalalic**
Fix for [#1893](https://github.com/tmpvar/jsdom/issues/1893)

### CODE REVIEW

**Comment by domenic** [comment]
Thanks, but this will need tests before we can accept it.

Since window.close() is somewhat of a specialty feature, those tests will be a bit special. Probably the best thing to do would be to copy https://github.com/tmpvar/jsdom/blob/master/test/api/basics.js into a new file named, maybe, from-outside.js? With the top-level describe being `"Test cases only possible to test from the outside"`.

**Comment by Enverbalalic** [comment]
I'm not as familiar with this project as you are, I'm still able to reproduce the same issue with the same code even if I remove "{ runScripts: "outside-only" }" if you think that that's what's causing this.

**Comment by domenic** [comment]
Heh, I can see the confusion. What I meant is that this can only be *tested* from the outside. You could not write a .html file that triggered this bug.

However it actually doesn't rely on running scripts at all, so yeah, the runScripts: "outside-only" option is unrelated.

**Comment by Enverbalalic** [comment]
So after running the tests the previous pull request was wrong. This one should be ok, complete with a test that confirms the behaviour.

**Pull request merged**
