### PR TITLE
Update to new webidl2js

### PR DESCRIPTION
**Pull request by TimothyGu**
- Overloads
- Enumerations
- Update some IDL fragments from specs

Needs https://github.com/jsdom/webidl2js/pull/86

### CODE REVIEW

**Comment by domenic** [comment]
I'm surprised there aren't more locations where we use enumerations and overloads...

**Comment by Zirro** [comment]
I've got another one in css-object-model - [`CSS.supports()`](https://drafts.csswg.org/css-conditional-3/#the-css-interface) - so I'm happy to see this get implemented.

**Comment by domenic** [comment]
It looks like this causes a bunch of XHR test failures?

**Comment by domenic** [comment]
Back to @TimothyGu to assess the XHR failures.

**Comment by TimothyGu** [comment]
Test failures (should be) fixed.

**Pull request merged**
