### PR TITLE
Changing StyleSheetList.prototype.item to match specification

### PR DESCRIPTION
**Pull request by Ginden**
Per [spec](https://drafts.csswg.org/cssom/#dom-stylesheetlist-item)
> The item(index) method must return the indexth CSS style sheet in the collection. If there is no indexth object in the collection, **then the method must return null.**

### CODE REVIEW

**Comment by domenic** [comment]
Test please?

**Comment by Ginden** [comment]
I doubt if tests in `test/level2/` are called anywhere, so I don't know where should I put this test.

`test/level2/style.js` is referenced by `test/worker-runner.js`. `test/worker-runner.js` is referenced by `test/worker.js`, but I couldn't find any file referencing `test/worker.js`.

Putting `throw new Error()` on top of file doesn't change output of `npm test`.

**Comment by Joris-van-der-Wel** [comment]
The file you are looking for is `test/runner`. test/level2 still has to be converted to mocha, you can use `npm run test-old` to run it. Normal `npm test` should also work, but you will have to wait a while because test/level2 will be on of the last tests that will be executed.

**Comment by Ginden** [comment]
Test added. BTW, tests seem to fail because of timeouts.

**Comment by domenic** [comment]
Merged as e91dec8195273d8690421b1e4763808874f4b1eb; thanks!

**Pull request closed without merging**
