### PR TITLE
Using HTTP headers from preflight response

### PR DESCRIPTION
**Pull request by fiftin**
Solution for https://github.com/tmpvar/jsdom/issues/1659

### CODE REVIEW

**Comment by domenic** [comment]
I'm going to merge this despite it not having tests, since testing CORS is really hard :-/.

**Comment by domenic** [comment]
Oh, actually, we can't merge this, since the addition of User-Agent to simple headers is against spec: https://fetch.spec.whatwg.org/#cors-safelisted-request-header

**Comment by domenic** [comment]
Closing per https://github.com/tmpvar/jsdom/issues/1659#issuecomment-267842178

**Comment by mbroadst** [comment]
@domenic it appears that part of this PR _should_ indeed be merged in. We're running jsdom tests against our local server, and failing miserably on CORS-related issues because the preflight headers aren't being forwarded to the request. I'm not sure whether adding `"user-agent"` to `simpleHeaders` is a good idea, but the second part of the commit does the job for us

**Pull request closed without merging**
