### PR TITLE
Added the obsolete Image constructor.

### PR DESCRIPTION
**Pull request by ssesha**
Test case: http://sneakerworldwide.com/product.php?productid=17527
This page does not throw any errors in Chrome.

Javascript execution in jsdom fails at new Image() with error. I found that the Image constructor was not implemented. Since, there was already HtmlImageElement defined, I thought to use it to define the image constructor.

Reference: https://developer.mozilla.org/en/docs/Web/API/HTMLImageElement.Image

### CODE REVIEW

**Comment by domenic** [comment]
Needs tests before it can be merged.

**Comment by vinothkr** [comment]
@domenic  Can you review this?

**Comment by domenic** [comment]
The test itself looks good, but for the formatting can you follow the style (and location) of the newer tests in https://github.com/tmpvar/jsdom/tree/master/test/living-html ?

I will merge this weekend.

**Comment by vinothkr** [comment]
@domenic Thanks, Fixed the structure of the tests.

**Comment by domenic** [comment]
Thanks! Merged as 599c8dcc12b7cdb109544e59deb81c71c1d9b9c5; releasing 3.0.0 shortly.

**Pull request closed without merging**
