### PR TITLE
Fixed iFrame sandbox attribute so setter does not utilize this.sandbox.value

### PR DESCRIPTION
**Pull request by palmerj3**

### CODE REVIEW

**Comment by domenic** [comment]
This is incorrect. The IDL given there is the IDL from the spec.

What is the actual problem you are trying to solve?

**Comment by palmerj3** [comment]
I noticed my unit tests would fail with code like so

```javascript
var sandboxParams = ['allow-top-navigation', 'allow-script'];
var iframe = document.createElement('iframe');
iframe.sandbox = sandboxParams.join(' ');
```

This would fail when the iframe setter would try to access this.sandbox.value.

**Comment by domenic** [comment]
It looks like jsdom does not support the sandbox attribute at all right now. The correct fix is commenting out that IDL line.

**Comment by palmerj3** [comment]
@domenic alright I'll close and re-submit. Thanks.

**Pull request closed without merging**
