### PR TITLE
Implement and test Element.prototype.closest

### LINKED ISSUE #1555: Support for Element.closest()
Hey folks, I was wondering whether there were plans to support [`Element.closest()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest) in jsdom?

### PR DESCRIPTION
**Pull request by apexskier**
Resolves #1555

### CODE REVIEW

**Comment by Sebmaster** [comment]
Please don't implement tests in the old test format.

Either look for a pre-existing test in the web-platform-tests and enable it, or implement it in that format in the to-upstream directory.

**Comment by apexskier** [comment]
Sorry, I was following the `matches` test pattern. It looks like a closest test [already exists](https://github.com/w3c/web-platform-tests/blob/c75cae4d1fcd0ed472b9110b14f6a8b5e2ce2759/dom/nodes/Element-closest.html), though, so I'll try enabling it.

**Comment by apexskier** [comment]
Okay, I tested enabling the ["dom/nodes/Element-closest.html"](https://github.com/w3c/web-platform-tests/blob/c75cae4d1fcd0ed472b9110b14f6a8b5e2ce2759/dom/nodes/Element-closest.html) test, but it fails because jsdom's matcher implementation isn't complete (["dom/nodes/Element-matches.html"](https://github.com/w3c/web-platform-tests/blob/c75cae4d1fcd0ed472b9110b14f6a8b5e2ce2759/dom/nodes/Element-matches.html) also fails). In the interest of enabling the `closest` method, I'd like to merge this PR and refactor the `matches` method (which this depends on) to enable both tests in the future.

**Comment by domenic** [comment]
We won't merge things that add more tests in the old format. If you could create some new tests in the to-upstream directory for closest(), that would be great. You can even base them off of the existing one that we can't get to pass; see others named -dont-upstream in that directory for an example of what we've done in the past.

**Comment by domenic** [comment]
Closing due to lack of response; looks like #1951 is attempting to pick this up.

**Pull request closed without merging**
