### PR TITLE
Add config option for custom resource loader.

### LINKED ISSUE #939: Providing a request field in config to circumvent requests
Essentially I'm thinking jsdom could allow you to provide your own custom request function to replace require("request") (which I think it uses internally but I could very well be wrong?). The benefit of this would be to allow you to use faster or different machinery to fetch resources. For example, on a server you could avoid network chatter by just grabbing resources directly from your database, or a stubbed out cache (this is my intended use). In testing, you could use it to mock without having to monkey-patch. Something like this:

jsdom.env(html, { request: ... });

### PR DESCRIPTION
**Pull request by tobie**
Closes #939.

### CODE REVIEW

**Comment by domenic** [comment]
This seems pretty reasonable. I'm worried though about the fact that now we need to document and commit to the public API for the until-now-private resourceLoader. It probably would need some cleanup before that's ready---the `fetch` you made seems like a nice start.

Also, I don't like using `this` as an implicit zeroth argument, so we'd want to pass that as the first argument.

**Comment by tobie** [comment]
I don't think there's a lot of use-cases for exposing the API beyond the fetch method itself, tbh.

What about passing the equivalent of a bound `.fetch()` method only, and optionally grouping `url`, `cookie` and `referrer` in an vanilla obj which can be passed to `fetch`, e.g.:

```js
require("jsdom").env({
  url: "http://example.com/",
  resourceLoader: function(fetch, resource, callback) {
    fetch(resource, function(err, body) {
      if (/\.js$/.test(resource.url.href)) {
        body = '"use strict";\n' + body;
      }
      callback(err, body)
    });
  },
  features: // …
});
```

Or even making `fetch` a method of the resource object itself:

```js
require("jsdom").env({
  url: "http://example.com/",
  resourceLoader: function(resource, callback) {
    resource.fetch(function(err, body) {
      if (/\.js$/.test(resource.url.href)) {
        body = '"use strict";\n' + body;
      }
      callback(err, body)
    });
  },
  features: // …
});
```

**Comment by domenic** [comment]
I like the latter a lot. Maybe just call it `defaultFetch` and we're good to go.

**Comment by domenic** [comment]
Also it would be nice to get a test similar to your last example in there.

**Comment by tobie** [comment]
Working on this now, it seems the [whole](https://github.com/tmpvar/jsdom/blob/3a75559/lib/jsdom/level2/html.js#L29) [cookie string](https://github.com/tmpvar/jsdom/blob/3a75559/lib/jsdom/level2/html.js#L111) is sent to the server instead of just the `key=value` pair. This seems like a violation of [RFC6265](http://tools.ietf.org/html/rfc6265#section-5.4).

The fix is simple (replace `document._cookie` by `document.cookie` in [line 29](https://github.com/tmpvar/jsdom/blob/3a75559/lib/jsdom/level2/html.js#L29)). Are you OK with me fixing it in this pull request or would you prefer a separate PR?

**Comment by tobie** [comment]
Went ahead and fixed that here. LMK if that's an issue for you.

**Comment by domenic** [comment]
Lovely, with a test too! Time to merge :D

**Comment by domenic** [comment]
Merged as bea2c9ed012624ec2aa0e3ba04705cfb454414e2 and 87e8d1f46166bb4e60744b80aa6133e1838b870c, and released as version 3.1.0!

**Pull request closed without merging**
