### PR TITLE
removeEventListener doesn't work when useCapture is specified

### PR DESCRIPTION
**Pull request by Sebmaster**
```javascript
var jsdom = require("jsdom");

jsdom.env(
  "<p id='test'></p>",
  function (err, window) {
	var ticks = 0,
		listener = function() { ticks++ },
		elm = window.document.getElementById('test');
	
	// Attach 
    elm.addEventListener('test', listener, false);
    
    // Dispatch
	event = new window.CustomEvent('test');
    elm.dispatchEvent(event);
    
    console.log(ticks); // 1
    
    // Detach
    elm.removeEventListener('test', listener);
    
    // Dispatch
	event = new window.CustomEvent('test');
    elm.dispatchEvent(event);
    
    console.log(ticks); // 2 (should be 1)
  }
);
```

Bad behavior with those values:

```javascript
elm.addEventListener('test', listener, false);
elm.removeEventListener('test', listener);

elm.addEventListener('test', listener);
elm.removeEventListener('test', listener, false);

elm.addEventListener('test', listener, undefined);
elm.removeEventListener('test', listener, false);

elm.addEventListener('test', listener, false);
elm.removeEventListener('test', listener, undefined);
```

Correct behavior with those values:

```javascript
elm.addEventListener('test', listener);
elm.removeEventListener('test', listener);

elm.addEventListener('test', listener, true);
elm.removeEventListener('test', listener, true);

elm.addEventListener('test', listener, false);
elm.removeEventListener('test', listener, false);

elm.addEventListener('test', listener, null);
elm.removeEventListener('test', listener, null);

elm.addEventListener('test', listener, undefined);
elm.removeEventListener('test', listener, undefined);
```

jsdom 7.2.1
node 4.1.2

### CODE REVIEW

**Comment by Sebmaster** [comment]
Attached PR

**Comment by domenic** [comment]
Why isn't this taken care of by the IDL conversion? `undefined` to `optional boolean` should give `false` automatically.

**Comment by Sebmaster** [comment]
Webidl spec says

> It is strongly suggested not to use default value of true for boolean-typed arguments, as this can be confusing for authors who might otherwise expect the default conversion of undefined to be used (i.e., false).

which sounds more like a `should not` instead of a `must not`.

**Comment by domenic** [comment]
That doesn't have anything to do with the Web IDL conversions though; it's just non-normative text guiding spec authors to not do `optional boolean capture = true`.

**Comment by Sebmaster** [comment]
Couldn't a spec describe special default behaviour in the actual description though? I'm not sure `= false` is implicit in this case.

**Comment by domenic** [comment]
A spec could define special case behavior. But this one doesn't. It's pretty clear:

- optional means "don't throw when undefined is passed"
- boolean means "convert argument using Boolean()"

**Comment by domenic** [comment]
Oh, I see what you mean, hmm.

**Comment by domenic** [comment]
Yeah, OK, makes sense.

What will happen if I pass `1`? Will webidl2js correctly convert that to `true`?

**Comment by Sebmaster** [comment]
Yeah, only `undefined` is special cased.

**Comment by domenic** [comment]
So uh this also needs tests

**Comment by Sebmaster** [comment]
Done :tada:

**Pull request merged**
