### PR TITLE
Swallowing errors in invokeEventListeners

### PR DESCRIPTION
**Pull request by ehpc**
Hi!
I've had some problem using jsdom with simple _jQuery.ajax.then_. There was an error inside _then_ callback and it was swallowed. So everything was fine, no errors, but I had never received any data. So I started debugging and found that piece of code. I think it it misleading to just swallow errors without any warning. Maybe it has some purpose in the big picture, but for my use case it was destructive.

### CODE REVIEW

**Comment by domenic** [comment]
Can you give a small (10-20 line) test case where this error manifests, so that we can use it as a regression test in the future?

I don't think the fix you propose here is the best way to do this, but once we have a small test case, we can use it to work on better solutions, like forwarding it to the jsdom virtual console.

**Comment by ehpc** [comment]
var jsdom = require('jsdom').jsdom,
	targetUrl = 'https://code.jquery.com/jquery-1.11.3.js';
	document = jsdom('<script src="' + targetUrl + '"></script>'),
	window = document.defaultView;

document.body.onload = function () {
	window.jQuery.ajax({
		url: targetUrl,
		type: 'GET',
		dataType: 'text',
		data: {},
		async: false
	}).then(function (data) {
		// The next line should throw something
		undefinedVariable.property = true;
		console.log('>>>DATA:', data.substring(0, 80));
	}, function (jqXHR, textStatus, errorThrown) {
		console.error('>>>ERROR:', textStatus, errorThrown);
	});
	console.log('body.onload end');
};

console.log('script end');

**Comment by domenic** [comment]
Ah, thank you. This is #1438 then. We should solve that in a different way.

**Comment by ehpc** [comment]
Ok, thanks.

**Pull request closed without merging**
