### PR TITLE
Convert browser & jsonp & level1 tests to mocha

### PR DESCRIPTION
**Pull request by Joris-van-der-Wel**
I have corrected `jscs` for "level1". However `eslint` for "level1" is too much work, there are about 2000 violations that would have to be fixed manually (I did run `eslint --fix` though)

### CODE REVIEW

**Comment by domenic** [comment]
Great stuff, thanks! Of course some of these should become to-upstream web platform tests, but baby steps.

**Comment by domenic** [comment]
All merged :)

**Comment by Ms2ger** [comment]
I occasionally submit tests from those test suites into wpt; https://bitbucket.org/ms2ger/old-dom-tests tracks my progress.

**Comment by Joris-van-der-Wel** [comment]
That's great, we plan to do the same with our tests so that we can submit them. For example https://github.com/tmpvar/jsdom/blob/master/test/living-dom/node-iterator.js contains a lot of tests which are not covered by WPT.

**Pull request merged**
