### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by TimothyGu**
Most updates are in-range updates to yarn.lock, though two major updates are included also. The change to test/api/methods.js is because of a bugfix in parse5.

### CODE REVIEW

**Comment by domenic** [comment]
Shouldn't we also update package.json?

**Comment by TimothyGu** [comment]
Definitely a good idea for parse5, though the others can be done optionally, since a new installation would pull those in anyway.

**Comment by domenic** [comment]
Sure, it just seems weird to encourage previous installations that upgrade to get different dependency versions than the one's we're testing against.

**Comment by TimothyGu** [comment]
package.json updated too.

**Pull request merged**
