### PR TITLE
Rewrite cloning, plus some other fixes

### PR DESCRIPTION
**Pull request by domenic**
Review appreciated. Started out with fixing #1142 but as usual I got carried away.

### CODE REVIEW

**Comment by Sebmaster** [comment]
What about the removed tests? Were they wrong again?

**Comment by domenic** [comment]
Yeah, they were cloning Attrs (which shouldn't even be Nodes) and were assuming you couldn't clone a doctype node.

**Comment by Sebmaster** [comment]
Without having looked at the spec yet, rest looks good to me.

**Comment by domenic** [comment]
@Sebmaster updated to use a symbol for cloning steps

**Pull request merged**
