### PR TITLE
Refactor events take 2

### PR DESCRIPTION
**Pull request by domenic**
Building on #1031. Right now I have to go to lunch but after I get back I can fix a few failing tests of DOMException hopefully. Then we'll have a new DOMException that we can use without requiring all of level1/core, which means that EventTarget can throw a DOMException without causing a circular dependency weirdness.

### CODE REVIEW

**Comment by domenic** [comment]
OK cool, got this working and ready for a review, @Sebmaster.

**Comment by Sebmaster** [comment]
What are we going to do with `window.addEventListener.call(myNode, ...)` now? We should probably also add a test for that.

**Comment by domenic** [comment]
I think we can fix that, probably using your technique, in a follow-up. But for now we're basically doing what we've always done and shadowing the prototype methods.

**Comment by Sebmaster** [comment]
Something is broken with the browser tests, need to fix that, but I haven't looked into it.

**Comment by domenic** [comment]
Oh, it's the let/const usage, cuz Sauce doesn't have Chrome 41 yet :-/. Hmm.

**Pull request merged**
